### ISSUE TITLE
GCB2T_FB2T is not found

### ISSUE THREAD

**Issue by auerswald** [lscheffler/bin2text#7]
## ℹ Computer information

- VFP version: 9 SP2
- FoxBin2PRG version: 1.21.03
- Bin2Text version: 1.3.0

## 📝 Provide detailed reproduction steps (if any)

command `DO InitMenu IN "C:\Program Files (x86)\Thor\Thor\Tools\Components\Bin2Text\bin2text.exe"`

### ✔️ Expected result

no errors

### ❌ Actual result

I can't say for sure because I don't know whether this component works.

i have tried different paths with the `WITH` parameter, i followed the instructions. it doesn't matter if a directory is git controlled. i only get this error and then can't configure the form because everything is disabled. i also can't close the form and have to close VFP completely. the documentation is really very good, except that the crucial installation steps are obviously not described sufficiently. for example, when installing via Thor, there is no '.app' at all, only the 'exe'.
by the way: it is a VFP9 installation and only thor and the two components bin2text and bin2prg are installed. bin2prg works without errors or problems. the bin2text component is a big mystery to me ;)

## 📷 Screenshots

<img width="393" alt="image" src="https://github.com/user-attachments/assets/5ef56b71-1825-43d2-ba14-62754943f02a">

**Comment by lscheffler** [comment]
@auerswald I'm sorry, somehow I missed the ticket.

**Comment by lscheffler** [comment]
Fixed in version 1.3.1
